"""user add to profiles field lazeload

Revision ID: 05e66ebbfc24
Revises: e711b08042d9
Create Date: 2022-06-20 21:47:05.956596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e66ebbfc24'
down_revision = 'e711b08042d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
