"""user profiles - joined

Revision ID: 0a4898847f2f
Revises: 05e66ebbfc24
Create Date: 2022-06-20 21:57:38.486868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4898847f2f'
down_revision = '05e66ebbfc24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
