"""add is_superuser field

Revision ID: 13df390e04c1
Revises: 0a4898847f2f
Create Date: 2022-07-23 09:14:32.210293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13df390e04c1'
down_revision = '0a4898847f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
